from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.models.user import UserDB
from app.schemas.user import UserCreate


def create_user(db: Session, user: UserCreate) -> UserDB:
    """
    Create a new user in the database.

    The service layer contains the actual business logic.
    The router will later be responsible only for handling
    the HTTP request and response.
    """

    new_user = UserDB(
        name=user.name,
    )

    try:
        # Add the new user to the current database session.
        db.add(new_user)

        # Commit permanently saves the new user in PostgreSQL.
        db.commit()

        # Refresh retrieves values generated by the database,
        # such as the newly assigned user_id.
        db.refresh(new_user)

        return new_user

    except SQLAlchemyError:
        # If the database operation fails, undo any pending changes.
        db.rollback()

        # Re-raise the original database error so the router
        # can decide how to present the error to the client.
        raise